### ISSUE TITLE
Going into extended canter crashes the game

### ISSUE THREAD

**Issue by Varghul** [AlaharranHonor/SWEquestrianM#124]
### What happened?

I was riding a maxed swem horse (not sure if this happens to other levels as I used the all xp potion on it) and walk-canter were working fine. I went to extended canter and it crashed my game almost immediately. This is the 2nd time it's happened (I tried it again since I wasn't sure if it was specifically the extended canter or not).

### What should happen?

The game should not crash when going faster than a canter.

### Mods

I took a screen shot since It's quite a few mods.
![image](https://user-images.githubusercontent.com/97770119/192103144-1b5093ee-cc24-48a5-be9e-99a6a43f3d26.png)

### SWEM Version

1.16.5-0.5.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 9/24/22 10:16 AM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:463) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:71) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:77) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:154) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.func_225623_a_(GeoEntityRenderer.java:53) ~[?:3.0.92] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2124) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1740) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/82517097.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:463) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:71) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:77) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:154) ~[?:3.0.92] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.func_225623_a_(GeoEntityRenderer.java:53) ~[?:3.0.92] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: creatures:peafowl (com.frikinzi.creatures.entity.PeafowlEntity)
	Entity ID: 169
	Entity Name: Peafowl
	Entity's Exact location: 1396.48, 64.00, 416.91
	Entity's Block location: World: (1396,64,416), Chunk: (at 4,4,0 in 87,26; contains blocks 1392,0,416 to 1407,255,431), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.frikinzi.creatures.client.render.PeafowlRenderer@2b14455c
	Location: 142.73,-3.22,58.62 - World: (142,-4,58), Chunk: (at 14,-1,10 in 8,3; contains blocks 128,0,48 to 143,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 80.15625
	Delta: 0.89994466
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2124) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1740) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Varghul'/119, l='ClientLevel', x=1253.82, y=65.61, z=358.29]]
	Chunk stats: Client Chunk Cache: 3969, 3362
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,64,208), Chunk: (at 0,4,0 in 5,13; contains blocks 80,0,208 to 95,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2320447 game time, 3168603 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:simplyseasons.mixins.json:client.SSClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/82517097.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2869739488 bytes (2736 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		UnionLib-1.16.5-3.3.7 (1).jar                     |UnionLib                      |unionlib                      |3.3.7               |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5+1.16.5.jar       |Player Animator               |playeranimator                |0.3.5+1.16.5        |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.107.jar                          |Just Enough Items             |jei                           |7.7.0.107           |DONE      |Manifest: NOSIGNATURE
		furnish-1.16.5-0.5.jar                            |Furnish                       |furnish                       |1.16.5-0.5          |DONE      |Manifest: NOSIGNATURE
		Floral Enchantment-1.16.5-1.3.0.jar               |Floral Enchantment            |floralench                    |1.16.5-1.3.0        |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.16.5-2.1.15.jar                    |Doggy Talents 2               |doggytalents                  |2.1.15              |DONE      |Manifest: NOSIGNATURE
		callablehorses-1.16.3-1.2.1.4.jar                 |Callable Horses               |callablehorses                |1.2.1.4             |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		WildFarmCraft 2.0.jar                             |WildFarmCraft                 |wildfarmcraft                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |Manifest: NOSIGNATURE
		Decoration+Mod+1.6+(Ver+1.16.5).jar               |Decoration and furniture mod  |decoration_mod                |1.6.0               |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-11.0.5-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.5       |DONE      |Manifest: NOSIGNATURE
		frikinzis-fauna-1.3.1-1.16.5.jar                  |Frikinzi's Fauna              |creatures                     |v1.3.0-1.16.5       |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.6               |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		Simply-Seasons-1.16.5-1.0.17 (1).jar              |Simply Seasons                |simplyseasons                 |1.16.5-1.0.17       |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		RevampedWolf-1.16.4-0.7.1.jar                     |RevampedWolf                  |revampedwolf                  |1.16.4-0.7.1        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.2-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		economyinc-1.6.9.4-1.16.5 (1).jar                 |Economy Inc.                  |economyinc                    |1.6.8               |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.5-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.5               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.4-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.4               |DONE      |Manifest: NOSIGNATURE
		swlm-1.16.5-1.1.1 (1).jar                         |Star Worm Lighting Mod        |swlm                          |1.16.5-1.1.1        |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.4.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE
		Craftable+Saddles+[1.16+All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		swdm-1.16.5-2.0.2 (1).jar                         |Star Worm Deco Mod            |swdm                          |1.16.5-2.0.2        |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.40.jar                   |Polymorph                     |polymorph                     |1.16.5-0.40         |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.16.4-1.7.2.jar          |Better Third Person           |betterthirdperson             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		CustomNPCs-1.16.5.20220515.jar                    |Custom NPCs                   |customnpcs                    |1.16.5.20220515     |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		nfm-2022.07.15-1.16.5.jar                         |Nosiphus Furniture Mod        |nfm                           |2022.07.15          |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.63.jar                          |Architectury                  |architectury                  |1.32.63             |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.0.0-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		simplycats-1.16.5-0.1.3 (1).jar                   |Simply Cats                   |simplycats                    |1.16.5-0.1.3        |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		exoticbirds-1.16.4-1.4.0.jar                      |Exotic Birds                  |exoticbirds                   |1.4.0               |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta32.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta32|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta11.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta11 |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.92.jar                  |GeckoLib                      |geckolib3                     |3.0.92              |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.5.0.jar                             |Star Worm Equestrian Mod      |swem                          |1.16.5-0.5.0        |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.16.5.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Penguin-Lib-1.16.5-0.4.3.jar                      |Penguin Lib                   |penguinlib                    |1.16.5-0.4.3        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: ed906315-8a4b-4264-bb52-efba85586b28
	Launched Version: 1.16.5-forge-36.2.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Kellourpack-3.3.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by MagnusHJensen** [comment]
This is not a problem on our side.
I commented on an issue that was created back in July.
https://github.com/frikinzi/frikinzis_fauna/issues/8

You can go there and upvote the issue, and hope fixes it :D
