### ISSUE TITLE
[Bug]: Ticking Entity crash

### ISSUE THREAD

**Issue by AsterMeer** [AlaharranHonor/SWEquestrianM#552]
### What happened?

Every time I try to mount a horse, the server crashes

### What should happen?

I should be able to tame and ride a horse

### Mods

forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		GeneticAnimals-0_6_40.jar                         |Genetic Animals               |eanimod                       |0_6_40              |DONE      |Manifest: NOSIGNATURE
		swlm-1.16.5-1.1.4.jar                             |Star Worm Lighting Mod        |swlm                          |1.16.5-1.1.4        |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.100.jar                 |GeckoLib                      |geckolib3                     |3.0.100             |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.5.2.12.jar                          |Star Worm Equestrian Mod      |swem                          |1.16.5-0.5.2.12     |DONE      |Manifest: NOSIGNATURE
		swdm-1.16.5-2.0.4.jar                             |Star Worm Deco Mod            |swdm                          |1.16.5-2.0.4        |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5+1.16.5.jar       |Player Animator               |playeranimator                |0.3.5+1.16.5        |DONE      |Manifest: NOSIGNATURE

### SWEM Version

swem-1.16.5-0.5.2.12

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/14/23 6:18 PM
Description: Ticking entity

java.lang.NoSuchMethodError: software.bernie.geckolib3.core.manager.AnimationFactory.getOrCreateAnimationData(Ljava/lang/Integer;)Lsoftware/bernie/geckolib3/core/manager/AnimationData;
	at com.alaharranhonor.swem.client.animation.PlayerAnimationController.tick(PlayerAnimationController.java:52) ~[?:1.16.5-0.5.2.12] {re:mixin,re:classloading}
	at net.minecraft.client.entity.player.AbstractClientPlayerEntity.func_70071_h_(AbstractClientPlayerEntity.java:550) ~[?:?] {re:mixin,xf:fml:forge:bows.0,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:bows.0,pl:mixin:APP:swem.mixins.json:client.AbstractClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1611) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2578) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70098_U(PlayerEntity.java:451) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70098_U(ClientPlayerEntity.java:786) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217420_a(ClientWorld.java:215) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:200) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$6921/1843700141.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:162) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1868987089.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.alaharranhonor.swem.client.animation.PlayerAnimationController.tick(PlayerAnimationController.java:52) ~[?:1.16.5-0.5.2.12] {re:mixin,re:classloading}
	at net.minecraft.client.entity.player.AbstractClientPlayerEntity.func_70071_h_(AbstractClientPlayerEntity.java:550) ~[?:?] {re:mixin,xf:fml:forge:bows.0,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:bows.0,pl:mixin:APP:swem.mixins.json:client.AbstractClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1611) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2578) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70098_U(PlayerEntity.java:451) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70098_U(ClientPlayerEntity.java:786) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217420_a(ClientWorld.java:215) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:200) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$6921/1843700141.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: swem:swem_horse (com.alaharranhonor.swem.entities.SWEMHorseEntity)
	Entity ID: 363
	Entity Name: . G O O S E .
	Entity's Exact location: 148.58, 4.00, 98.28
	Entity's Block location: World: (148,4,98), Chunk: (at 4,0,2 in 9,6; contains blocks 144,0,96 to 159,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: [ClientPlayerEntity['AsterMeridia'/1715, l='ClientLevel', x=148.49, y=4.00, z=100.77]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:162) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['AsterMeridia'/1715, l='ClientLevel', x=148.49, y=4.00, z=100.77]]
	Chunk stats: Client Chunk Cache: 2209, 1763
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,4,240), Chunk: (at 0,0,0 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 65740018 game time, 5756 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:458) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1868987089.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 632254720 bytes (602 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		GeneticAnimals-0_6_40.jar                         |Genetic Animals               |eanimod                       |0_6_40              |DONE      |Manifest: NOSIGNATURE
		swlm-1.16.5-1.1.4.jar                             |Star Worm Lighting Mod        |swlm                          |1.16.5-1.1.4        |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.100.jar                 |GeckoLib                      |geckolib3                     |3.0.100             |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.5.2.12.jar                          |Star Worm Equestrian Mod      |swem                          |1.16.5-0.5.2.12     |DONE      |Manifest: NOSIGNATURE
		swdm-1.16.5-2.0.4.jar                             |Star Worm Deco Mod            |swdm                          |1.16.5-2.0.4        |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5+1.16.5.jar       |Player Animator               |playeranimator                |0.3.5+1.16.5        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 21ac9d0e-b634-4aac-a081-d5861ecb3231
	Launched Version: 1.16.5-forge-36.2.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.44.05 27.20.11044.5003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 3250U with Radeon Graphics
```

**Comment by MagnusHJensen** [comment]
Try a new version of geckolib

**Comment by MagnusHJensen** [comment]
And update SWEM
